remote_theme: "mmistakes/minimal-mistakes"

title: "From Minerals to Megawatts"
description: "Team page for our work and publications"

# Required for correct absolute URLs on a user site
url: "https://oitzingermaximilian.github.io"
baseurl: ""

# Keep plugins minimal and GitHub Pages–compatible
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
